# runtime: python39
# handlers:
#   - url: /static
#     static_dir: static
#   - url: /.*
#     static_files: index.html
#     upload: index.html

runtime: python39
handlers:
  - url: /.*
    static_files: index.html
    upload: index.html

  - url: /static
    static_dir: static