steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', '.', 'gs://${_ARTIFACTS_BUCKET}/${_ARTIFACTS_PATH}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ $_ENV == "dev" ]]; then
          # Despliega en el ambiente de desarrollo
          gcloud app deploy --project=${PROJECT_ID} --version=${_ENV}-${_APP_VERSION} --no-promote

        if [[ $_ENV == "prod" ]]; then
          # Despliega en el ambiente de desarrollo
          gcloud app deploy --project=${PROJECT_ID} --version=${_ENV}-${_APP_VERSION} --promote --stop-previous-version

        fi
